name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    branches: [master]
    workflows: ["Update data"]
    types: [completed]

jobs:
  deploy:
    uses: EqualStreetNames/equalstreetnames/.github/workflows/reusable-deploy.yml@master
    permissions:
      pages: write
      id-token: write
    secrets: inherit
    with:
      country: france
      city: crest
